// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"BaseProjectGolang/internal/bootstrap"
	"BaseProjectGolang/internal/command"
	"BaseProjectGolang/internal/config"
	"BaseProjectGolang/internal/dependency"
	"BaseProjectGolang/internal/http/controller"
	"BaseProjectGolang/internal/http/controller/examplectr"
	"BaseProjectGolang/internal/http/middleware"
	"BaseProjectGolang/internal/http/middleware/context"
	"BaseProjectGolang/internal/infrastructure/database"
	"BaseProjectGolang/internal/infrastructure/database/orm/plugin"
	"BaseProjectGolang/internal/infrastructure/database/orm/repository/examplerep"
	"BaseProjectGolang/internal/usecase/exampleusc"
	"BaseProjectGolang/internal/validation"
	"BaseProjectGolang/pkg/fasthttpmock"
	"BaseProjectGolang/pkg/log"
	"github.com/valyala/fasthttp"
)

// Injectors from flora_injector.go:

func InitializeContainer() (*FloraContainer, func(), error) {
	config := Provide_Start_NewStart()
	loggerConfig := Provide_LoggerConfig_ProvideLoggerConfig(config)
	logger := log.NewLogger(loggerConfig)
	scheduler := command.NewScheduler(config, logger)
	baseController := controller.NewBaseController(config)
	exampleRepository := examplerep.NewExampleRepository()
	exampleHandler := exampleusc.NewExampleHandler(config, exampleRepository)
	xValidator := validation.NewXValidator(config)
	exampleController := examplectr.NewExampleController(baseController, exampleHandler, xValidator)
	dataBase, err := database.NewDataBase(config, logger)
	if err != nil {
		return nil, nil, err
	}
	globalMiddleware := middleware.NewGlobalMiddleware(config, dataBase)
	setupCtxQB := context.NewSetupCtxQB(dataBase)
	client := Provide_ClientConfig_ProvideClient()
	handlers := dependency.NewHandlers(globalMiddleware, baseController, setupCtxQB, exampleController)
	registrationPlugin := plugin.NewRegistrationPlugin(dataBase)
	wrapClient := fasthttpmock.NewWrapClient(client)
	app, err := bootstrap.NewApp(config, handlers, dataBase, scheduler, wrapClient, logger, registrationPlugin)
	if err != nil {
		return nil, nil, err
	}
	floraContainer := &FloraContainer{
		Logger:             logger,
		Scheduler:          scheduler,
		BaseController:     baseController,
		ExampleHandler:     exampleHandler,
		XValidator:         xValidator,
		ExampleController:  exampleController,
		DataBase:           dataBase,
		GlobalMiddleware:   globalMiddleware,
		SetupCtxQB:         setupCtxQB,
		Client:             client,
		Handlers:           handlers,
		LoggerConfig:       loggerConfig,
		Config:             config,
		RegistrationPlugin: registrationPlugin,
		WrapClient:         wrapClient,
		App:                app,
		ExampleRepository:  exampleRepository,
	}
	return floraContainer, func() {
	}, nil
}

// flora_injector.go:

func Provide_ClientConfig_ProvideClient() *fasthttp.Client {
	cfg := dependency.ClientConfig{}

	val := cfg.ProvideClient()
	return val

}

func Provide_LoggerConfig_ProvideLoggerConfig(p0 *config.Config) log.LoggerConfig {
	cfg := dependency.LoggerConfig{}

	val := cfg.ProvideLoggerConfig(p0)
	return val

}

func Provide_Start_NewStart() *config.Config {
	cfg := dependency.Start{}

	val := cfg.NewStart()
	return val

}

type FloraContainer struct {
	Logger *log.Logger

	Scheduler *command.Scheduler

	BaseController *controller.BaseController

	ExampleHandler *exampleusc.ExampleHandler

	XValidator *validation.XValidator

	ExampleController *examplectr.ExampleController

	DataBase *database.DataBase

	GlobalMiddleware *middleware.GlobalMiddleware

	SetupCtxQB *context.SetupCtxQB

	Client *fasthttp.Client

	Handlers *dependency.Handlers

	LoggerConfig log.LoggerConfig

	Config *config.Config

	RegistrationPlugin *plugin.RegistrationPlugin

	WrapClient *fasthttpmock.WrapClient

	App *bootstrap.App

	ExampleRepository *examplerep.ExampleRepository
}
