// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"BaseProjectGolang/internal/bootstrap"
	"BaseProjectGolang/internal/command"
	"BaseProjectGolang/internal/config"
	"BaseProjectGolang/internal/dependency"
	"BaseProjectGolang/internal/http/controller"
	auth2 "BaseProjectGolang/internal/http/controller/auth"
	"BaseProjectGolang/internal/http/middleware"
	"BaseProjectGolang/internal/http/middleware/auth"
	"BaseProjectGolang/internal/http/middleware/context"
	"BaseProjectGolang/internal/infrastructure/database"
	"BaseProjectGolang/internal/infrastructure/database/orm/plugin"
	"BaseProjectGolang/internal/infrastructure/database/orm/repository/token"
	"BaseProjectGolang/internal/infrastructure/database/orm/repository/user"
	"BaseProjectGolang/internal/usecase/token/access/create"
	"BaseProjectGolang/internal/usecase/user/auth/login"
	"BaseProjectGolang/internal/validation"
	"BaseProjectGolang/pkg/fasthttpmock"
	"BaseProjectGolang/pkg/log"
	"BaseProjectGolang/pkg/mail"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, db *database.DataBase) (*bootstrap.App, error) {
	globalMiddleware := middleware.NewGlobalMiddleware(cfg, db)
	jwtAddAuthUserInCtx := auth.NewJwtAddAuthUserInCtx(db, cfg)
	baseController := controller.NewBaseController(cfg)
	setupCtxQB := context.NewSetupCtxQB(db)
	repository := user.NewUserRepository()
	accessTokenRepository := token.NewTokenRepository()
	handler := create.NewCreateAccessTokenHandler(cfg, repository, accessTokenRepository)
	loginHandler := login.NewLoginHandler(cfg, repository, accessTokenRepository, handler)
	xValidator := validation.NewValidator(cfg)
	authController := auth2.NewAuthController(baseController, loginHandler, xValidator, repository, accessTokenRepository)
	handlers := dependency.NewHandlers(globalMiddleware, jwtAddAuthUserInCtx, baseController, setupCtxQB, authController)
	loggerConfig := GetLoggerConfig(cfg)
	logger := log.InitLogger(loggerConfig)
	scheduler := command.NewScheduler(cfg, logger)
	client := dependency.NewClient()
	wrapClient := fasthttpmock.NewWrapClient(client)
	registrationPlugin := plugin.NewRegistrationPlugin(db)
	app, err := bootstrap.Bootstrap(cfg, handlers, db, scheduler, wrapClient, logger, registrationPlugin)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

func GetMailConfig(cfg *config.Config) *mail.GomailServiceConfig {
	return cfg.Mail
}

func GetLoggerConfig(cfg *config.Config) log.LoggerConfig {
	return cfg.Logs
}
