// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package enum

import (
	"errors"
	"fmt"
)

const (
	// ExampleEnumBad is a ExampleEnum of type bad.
	ExampleEnumBad ExampleEnum = "bad"
	// ExampleEnumGood is a ExampleEnum of type good.
	ExampleEnumGood ExampleEnum = "good"
	// ExampleEnumNeutral is a ExampleEnum of type neutral.
	ExampleEnumNeutral ExampleEnum = "neutral"
)

var ErrInvalidExampleEnum = errors.New("not a valid ExampleEnum")

// String implements the Stringer interface.
func (x ExampleEnum) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ExampleEnum) IsValid() bool {
	_, err := ParseExampleEnum(string(x))
	return err == nil
}

var _ExampleEnumValue = map[string]ExampleEnum{
	"bad":     ExampleEnumBad,
	"good":    ExampleEnumGood,
	"neutral": ExampleEnumNeutral,
}

// ParseExampleEnum attempts to convert a string to a ExampleEnum.
func ParseExampleEnum(name string) (ExampleEnum, error) {
	if x, ok := _ExampleEnumValue[name]; ok {
		return x, nil
	}
	return ExampleEnum(""), fmt.Errorf("%s is %w", name, ErrInvalidExampleEnum)
}

// MarshalText implements the text marshaller method.
func (x ExampleEnum) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ExampleEnum) UnmarshalText(text []byte) error {
	tmp, err := ParseExampleEnum(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ExampleEnum) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
