basePath: /api
definitions:
  dto.ExampleRequest:
    properties:
      example_data:
        type: string
    type: object
  dto.ExampleResponse:
    properties:
      example_data:
        type: string
    type: object
  error.HTTPError:
    properties:
      data:
        additionalProperties: true
        type: object
      message: {}
      metadata:
        additionalProperties: true
        type: object
      statusCode:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
  description: Monitoring API
  title: Monitoring service
  version: "1.0"
paths:
  /api/example:
    post:
      consumes:
      - application/json
      description: Example endpoint
      parameters:
      - description: Dto для логина
        in: body
        name: dto.ExampleRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ExampleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ExampleResponse'
        default:
          description: The body of any response with an error
          schema:
            $ref: '#/definitions/error.HTTPError'
      summary: Example endpoint
      tags:
      - Example
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
